#!/usr/bin/env python3
"""The processor's pin map, written from the netlist rather than beside it.

⛔ A PIN MAP IS THE ONE THING IN FIRMWARE THAT IS NOT FIRMWARE'S TO DECIDE. It is
the schematic, restated in C, and every project that types it a second time
eventually has a board and an image that disagree about which pin is a chip
select. This one is generated: netlist.py says P2.10 carries CS_RADAR_R, so
sb_pinmap.h says P2.10 carries CS_RADAR_R, and there is no third place where a
human could put something else.

⭐ IT ALSO MAKES THE REASSIGNMENT SAFE. Routing moved the whole P2 block around —
signals that had to travel east were on the package's west edge, which cost
sixteen unconnected pads — and the only reason that was a cheap change is that
the firmware addresses pins through symbolic ids. This file is what turns those
ids back into silicon, and it is regenerated when the netlist moves.

⚠️ THE NAMES COME FROM THE nRF54L15 DATASHEET, via netlist.py's pin table: a pin
called "P2.05/CSN" is port 2, pin 5. Nothing here knows what an nRF is beyond
that convention, which is why it is asserted rather than assumed — a pin whose
name does not parse is an error, not a skipped line.

Usage:  python3 hardware/generate_pinmap.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import netlist as nl                # noqa: E402

TARGET = os.path.join(os.path.dirname(HERE), "firmware", "target")
OUT = os.path.join(TARGET, "src", "sb_pinmap.h")
OVERLAY = os.path.join(TARGET, "boards", "smartbag.overlay")

# HAL pin id -> the net that carries it. ⚠️ The left column is firmware/sb_hal.h's
# enum and the right is netlist.py's net name; this dict is the only place the
# two vocabularies meet.
HAL_PINS = [
    ("SB_PIN_RADAR_EN", "RADAR_EN"),
    ("SB_PIN_RADAR_IRQ_L", "RADAR_IRQ_L"),
    ("SB_PIN_RADAR_IRQ_R", "RADAR_IRQ_R"),
    ("SB_PIN_TOF_XSHUT", "TOF_XSHUT"),
    ("SB_PIN_TOF_INT", "TOF_INT"),
    ("SB_PIN_IMU_INT1", "IMU_INT1"),
    ("SB_PIN_HALL", "HALL_OUT"),
    ("SB_PIN_PMIC_IRQ", "PMIC_IRQ"),
    ("SB_PIN_IR_LED_EN", "IR_LED_EN"),
]

CHIP_SELECTS = [("SB_CS_RADAR_L", "CS_RADAR_L"),
                ("SB_CS_RADAR_R", "CS_RADAR_R"),
                ("SB_CS_CAMERA", "CS_CAM")]

MUX = ["MUX_S0", "MUX_S1", "MUX_S2", "MUX_S3"]
BUS = [("SPI_SCK", "SCK"), ("SPI_MOSI", "MOSI"), ("SPI_MISO", "MISO"),
       ("I2C_SDA", "SDA"), ("I2C_SCL", "SCL")]
# The six transimpedance outputs the multiplexer sweeps, in row order.
ADC_ROWS = ["ADC0", "ADC1", "ADC2", "ADC3", "ADC4", "ADC5"]


def processor_pins():
    """{net: (port, pin)} for every GPIO of U1, out of the netlist."""
    u1 = next(p for p in nl.PARTS if p[0] == "U1")
    out = {}
    for _num, name, _et, net in u1[5]:
        m = re.match(r"P(\d)\.(\d\d)", name)
        if not m:
            continue                       # SWD, XTAL, ANT, DCC, supplies
        out[net] = (int(m.group(1)), int(m.group(2)))
    return out


def main():
    pins = processor_pins()
    missing = [n for _, n in HAL_PINS + CHIP_SELECTS if n not in pins]
    missing += [n for n in MUX + ADC_ROWS + ["MUX_EN_N", "VSYS_SNS"]
                if n not in pins]
    missing += [n for n, _ in BUS if n not in pins]
    if missing:
        sys.exit(f"nets with no processor pin in netlist.py: {missing}")

    def row(net):
        port, pin = pins[net]
        return port, pin

    L = ['/* GENERATED by hardware/generate_pinmap.py — do not edit.',
         ' *',
         ' * ⛔ THE SCHEMATIC, RESTATED IN C. Every number below is read out of',
         ' * hardware/netlist.py, which is the same file the board and the',
         ' * schematic are built from. Editing this header by hand makes the',
         ' * image disagree with the copper, silently, and the only symptom is a',
         ' * peripheral that does not answer.',
         ' *',
         ' * ⚠️ Port and pin, not a Zephyr device: the devicetree in',
         ' * boards/smartbag.overlay is where these become gpio0/gpio1/gpio2',
         ' * handles. This header is what the overlay and the C agree on.',
         ' */',
         '#ifndef SB_PINMAP_H',
         '#define SB_PINMAP_H',
         '',
         '#include "sb_hal.h"',
         '',
         '/* {port, pin} for every id in sb_hal.h\'s pin enum, in enum order. */',
         'static const struct { uint8_t port, pin; } sb_pinmap[SB_PIN_COUNT] = {']
    for sym, net in HAL_PINS:
        port, pin = row(net)
        L.append(f"    [{sym}] = {{{port}, {pin:>2}}},        /* {net} */")
    L += ['};', '',
          '/* Chip selects, in sb_cs order. */',
          'static const struct { uint8_t port, pin; } sb_cs_pins[SB_CS_COUNT] = {']
    for sym, net in CHIP_SELECTS:
        port, pin = row(net)
        L.append(f"    [{sym}] = {{{port}, {pin:>2}}},        /* {net} */")
    L += ['};', '',
          '/* The FSR multiplexer: four select lines and an active-low enable. */',
          'static const struct { uint8_t port, pin; } sb_mux_sel[4] = {']
    for net in MUX:
        port, pin = row(net)
        L.append(f"    {{{port}, {pin:>2}}},                  /* {net} */")
    p_en, n_en = row("MUX_EN_N")
    L += ['};',
          f'#define SB_MUX_EN_PORT {p_en}',
          f'#define SB_MUX_EN_PIN  {n_en}      /* MUX_EN_N, active low */',
          '',
          '/* The six row amplifiers, as SAADC analog inputs. ⚠️ AINn is chosen by',
          ' * the pin, not by an index: on nRF54L each analog-capable pin maps to',
          ' * one AIN, and netlist.py records which by naming it. */',
          'static const struct { uint8_t port, pin; } sb_adc_rows[6] = {']
    for net in ADC_ROWS:
        port, pin = row(net)
        L.append(f"    {{{port}, {pin:>2}}},                  /* {net} */")
    p_v, n_v = row("VSYS_SNS")
    L += ['};',
          f'#define SB_VSYS_SNS_PORT {p_v}',
          f'#define SB_VSYS_SNS_PIN  {n_v}',
          '']
    for net, short in BUS:
        port, pin = row(net)
        L += [f'#define SB_{short}_PORT {port}', f'#define SB_{short}_PIN  {pin}']
    L += ['', '#endif /* SB_PINMAP_H */', '']

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print(f"OK  {OUT}  ({len(HAL_PINS)} pins, {len(CHIP_SELECTS)} chip selects, "
          f"{len(ADC_ROWS)} analog rows)")
    write_overlay(pins)


def write_overlay(pins):
    """The devicetree the same numbers imply, so nobody types them twice.

    ⛔ THE JEITA THRESHOLDS WOULD OTHERWISE LIVE IN THREE PLACES. They are in the
    cell's datasheet, mirrored into hardware/bom.py, asserted against
    firmware/sb_power.h — and Zephyr's nPM1300 charger driver wants them in the
    devicetree as well, which is a fourth. Generating the overlay makes the
    fourth a copy rather than a decision.

    ⭐ AND THE PMIC IS A DRIVER, NOT A REGISTER MAP. Nordic ships one; writing
    I2C writes against register addresses recalled from memory is exactly the
    kind of invention this project spent a fortnight removing from its bill of
    materials.
    """
    sys.path.insert(0, HERE)
    import bom                                                # noqa: E402
    cell = bom.BOM["BT1"]
    cold, cool, warm, hot = cell["charge_bands_c"]

    def gp(net):
        port, pin = pins[net]
        return f"&gpio{port} {pin} GPIO_ACTIVE_HIGH"

    text = f"""/* GENERATED by hardware/generate_pinmap.py — do not edit.
 *
 * The board, as Zephyr needs to hear it. Every pin below is netlist.py's and
 * every charge threshold is the cell's own datasheet, via hardware/bom.py.
 *
 * ⚠️ This overlays the nRF54L15 DK, which is the only nRF54L15 board that can be
 * bought today. The SmartBag board is the same silicon with a different pin map,
 * and that pin map is what this file is.
 */

/* ⛔ I2C21 AND NOT I2C20. On nRF54L15 the peripheral instances are shared: SPI20,
 * SPIM20, TWIM20 and UARTE20 are the same block, and enabling two of them stops
 * the build with a static assertion rather than misbehaving at runtime. The DK
 * puts its console on uart20, so the bus had to move — and on the SmartBag board,
 * which has no console UART, instance 20 would have been free and this would
 * have been discovered on silicon instead.
 *
 * ⚠️ EVERY PINCTRL NODE NEEDS A SLEEP STATE AS WELL AS A DEFAULT. The board's
 * own devicetree gives spi00 both, so an overlay that replaces pinctrl-names
 * with a single "default" leaves pinctrl-1 defined and unnamed — and the build
 * stops with "has 1 strings, expected 2". It is also not busywork: the sleep
 * state is what disconnects the pins when the peripheral is powered down, and
 * this design spends almost all of its life powered down. */
&pinctrl {{
    spi00_default: spi00_default {{
        group1 {{
            psels = <NRF_PSEL(SPIM_SCK, {pins['SPI_SCK'][0]}, {pins['SPI_SCK'][1]})>,
                    <NRF_PSEL(SPIM_MOSI, {pins['SPI_MOSI'][0]}, {pins['SPI_MOSI'][1]})>,
                    <NRF_PSEL(SPIM_MISO, {pins['SPI_MISO'][0]}, {pins['SPI_MISO'][1]})>;
        }};
    }};

    spi00_sleep: spi00_sleep {{
        group1 {{
            psels = <NRF_PSEL(SPIM_SCK, {pins['SPI_SCK'][0]}, {pins['SPI_SCK'][1]})>,
                    <NRF_PSEL(SPIM_MOSI, {pins['SPI_MOSI'][0]}, {pins['SPI_MOSI'][1]})>,
                    <NRF_PSEL(SPIM_MISO, {pins['SPI_MISO'][0]}, {pins['SPI_MISO'][1]})>;
            low-power-enable;
        }};
    }};

    i2c21_default: i2c21_default {{
        group1 {{
            psels = <NRF_PSEL(TWIM_SDA, {pins['I2C_SDA'][0]}, {pins['I2C_SDA'][1]})>,
                    <NRF_PSEL(TWIM_SCL, {pins['I2C_SCL'][0]}, {pins['I2C_SCL'][1]})>;
            bias-pull-up;
        }};
    }};

    i2c21_sleep: i2c21_sleep {{
        group1 {{
            psels = <NRF_PSEL(TWIM_SDA, {pins['I2C_SDA'][0]}, {pins['I2C_SDA'][1]})>,
                    <NRF_PSEL(TWIM_SCL, {pins['I2C_SCL'][0]}, {pins['I2C_SCL'][1]})>;
            low-power-enable;
        }};
    }};
}};

&spi00 {{
    status = "okay";
    pinctrl-0 = <&spi00_default>;
    pinctrl-1 = <&spi00_sleep>;
    pinctrl-names = "default", "sleep";
    /* ⚠️ No cs-gpios: there are three devices on this bus and one CSN pin, so
     * the selects are plain GPIOs driven by sb_hal_zephyr.c. */
}};

&i2c21 {{
    status = "okay";
    pinctrl-0 = <&i2c21_default>;
    pinctrl-1 = <&i2c21_sleep>;
    pinctrl-names = "default", "sleep";
    clock-frequency = <I2C_BITRATE_FAST>;

    npm1300: pmic@6b {{
        compatible = "nordic,npm1300";
        reg = <0x6b>;

        npm1300_charger: charger {{
            compatible = "nordic,npm1300-charger";
            /* From Jauch LP523450JU: 4.2 V termination, 1.0 C = {cell['full_ma']} mA. */
            term-microvolt = <4200000>;
            current-microamp = <{cell['full_ma'] * 1000}>;
            /* ⛔ The cell's own bands, not lithium's in general. */
            dischg-limit-microamp = <1000000>;
            vbus-limit-microamp = <500000>;
            thermistor-ohms = <10000>;
            thermistor-beta = <3435>;
            thermistor-cold-millidegrees = <{cold * 1000}>;
            thermistor-cool-millidegrees = <{cool * 1000}>;
            thermistor-warm-millidegrees = <{warm * 1000}>;
            thermistor-hot-millidegrees = <{hot * 1000}>;
            charging-enable;
        }};
    }};

    imu@68 {{
        compatible = "bosch,bmi270";
        reg = <0x68>;
        irq-gpios = <{gp('IMU_INT1')}>;
    }};

    tof@29 {{
        compatible = "st,vl53l1x";
        reg = <0x29>;
        xshut-gpios = <{gp('TOF_XSHUT')}>;
        int-gpios = <{gp('TOF_INT')}>;
    }};
}};

&adc {{
    status = "okay";
    #address-cells = <1>;
    #size-cells = <0>;
"""
    for i, net in enumerate(ADC_ROWS):
        port, pin = pins[net]
        text += f"""
    channel@{i} {{
        reg = <{i}>;
        zephyr,gain = "ADC_GAIN_1_4";
        zephyr,reference = "ADC_REF_VDD_1_4";
        zephyr,acquisition-time = <ADC_ACQ_TIME_DEFAULT>;
        zephyr,input-positive = <NRF_SAADC_AIN{i}>;   /* {net}, P{port}.{pin:02d} */
        zephyr,resolution = <12>;
    }};
"""
    text += "};\n"
    os.makedirs(os.path.dirname(OVERLAY), exist_ok=True)
    with open(OVERLAY, "w") as f:
        f.write(text)
    print(f"OK  {OVERLAY}  (JEITA {cold}/{cool}/{warm}/{hot} C, "
          f"{cell['full_ma']} mA, from the cell's datasheet)")


if __name__ == "__main__":
    main()
