#!/usr/bin/env python3
"""What a test house will ask for, and what nobody here can answer.

⛔ THIS REPOSITORY HAS NEVER MENTIONED CERTIFICATION AND THAT IS THE LARGEST
SILENT GAP IN IT. A product with a Bluetooth radio, TWO 60 GHz radars, a
wireless power receiver and a lithium cell does not become a product because its
DRC is clean. It becomes a product when a notified body and a test lab say so,
and neither of them has heard of this.

⭐ WHAT THIS FILE CAN HONESTLY DO IS TWO THINGS. It can list the frameworks that
apply — which is knowable — and it can produce the equipment table a lab asks
for in its first email, which this repository happens to hold exactly: what
radiates, at what frequency, at what power, for how long, out of what antenna.
Every number in that table comes from bom.py and thermal/budget.py rather than
from anybody's memory.

⛔ WHAT IT REFUSES TO DO IS QUOTE CLAUSE NUMBERS IT IS NOT SURE OF. A wrong
standard reference in a compliance plan is worse than a blank: it gets believed,
budgeted for and scheduled, and the mistake surfaces at the lab. Where the exact
applicable standard depends on a judgement a test house makes — and for the
60 GHz radars it does — this says so and leaves the question open, with the
question written out so somebody can ask it.

⚠️ AND NOTHING HERE IS LEGAL ADVICE. It is a list of what to go and find out.

Usage:  python3 tools/compliance.py       (writes docs/compliance.md)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "hardware"))

import bom                          # noqa: E402
import dimensions as d              # noqa: E402

OUT = os.path.join(ROOT, "docs", "compliance.md")


def radiators():
    """Everything on the board that emits, from the BOM and the power budget."""
    return [
        dict(what="Bluetooth LE", part=bom.BOM["U1"]["mpn"],
             band="2400–2483.5 MHz", how="chip antenna " + bom.BOM["AE1"]["mpn"],
             duty="advertising 1 ms/s; a connection during a sync",
             note="intentional radiator. The one everybody expects."),
        dict(what="60 GHz radar ×2", part=bom.BOM["U2"]["mpn"],
             band="57–64 GHz", how="antenna inside the package",
             duty="≈50 ms per event, ≈40 events a day",
             note="⛔ THE HARD ONE. Two of them, and they are the reason this "
                  "document exists."),
        dict(what="wireless power receiver", part=bom.BOM["U11"]["mpn"],
             band="≈100–205 kHz (WPC)",
             how="Ø48 mm coil, " + bom.BOM["L_COIL"]["mpn"],
             duty="only while on a pad",
             note="a receiver, not a transmitter — but it is part of the "
                  "system a lab measures."),
    ]


def main():
    cell = bom.BOM["BT1"]
    rows = "\n".join(
        f"| **{r['what']}** | {r['part']} | {r['band']} | {r['how']} | "
        f"{r['duty']} | {r['note']} |" for r in radiators())

    text = f"""# SmartBag — what has to be certified, and what nobody has asked yet

⚠️ **Generated by `tools/compliance.py` from `hardware/bom.py` and
`thermal/budget.py`.** The equipment table is derived, so it cannot drift from
the design. The rest is a list of what to go and find out.

⛔ **Nothing here is legal advice and no clause number is quoted unless it is
certain.** A wrong standard reference in a compliance plan is worse than a blank
one: it gets believed, budgeted and scheduled, and the mistake surfaces at the
lab. Where the applicable standard depends on a judgement a test house makes,
this says so.

---

## 1 · What radiates

This is the table a test house asks for first, and it is the reason this file is
generated rather than written.

| | part | band | antenna | duty cycle | |
|---|---|---|---|---|---|
{rows}

Average power of the whole product, from `thermal/budget.py`: **0.15 mW**. The
duty cycles above are not incidental — they are the architecture. Nothing polls;
each stage is armed by the one before it.

## 2 · Europe

The product is radio equipment, so it falls under the **Radio Equipment
Directive (2014/53/EU)**. Under RED a manufacturer self-declares against
harmonised standards, and where no harmonised standard covers a case, a
**notified body** has to be involved.

| what | status |
|---|---|
| **2.4 GHz BLE** | ✅ well-trodden. A wideband data transmission module in this band is the most tested thing in consumer electronics, and the SoC vendor supplies test reports for its own radio. The *product* still has to be measured — the antenna is on this board, next to this ground plane, inside leather. |
| **60 GHz radar ×2** | ⛔ **the open question.** 57–64 GHz is licence-exempt in the EU for short-range devices, but which harmonised standard applies to a pulsed coherent radar in a consumer bag — and whether one applies at all — is a judgement for a test house. **Ask Acconeer first**: they sell the A121 into consumer products and will know what route their customers take, and whether any of it transfers. |
| **EMC** | applies. Immunity and emissions for a radio product. |
| **RF exposure** | applies. Two radars and a BLE radio against a body, in a bag carried against a hip. The powers are tiny; the assessment still has to exist. |
| **Electrical safety** | applies to the product as a whole, including the charging path. |
| **Battery** | the cell is already **UN 38.3** and **IEC 62133-2** certified by Jauch — that is on its datasheet. ⚠️ The finished product is a separate matter. |
| **RoHS / REACH** | applies. Every part in `hardware/bom.py` is a current catalogue part from a major distributor, so compliance data exists for all of them — but it has to be collected. |
| **WEEE** | applies. It is an electronic product with a built-in battery. |

## 3 · United States

| what | status |
|---|---|
| **2.4 GHz BLE** | standard FCC certification for an intentional radiator in the ISM band. |
| **60 GHz radar** | ⛔ **do not assume this is the same as Europe.** The rules for 57–64 GHz field-disturbance sensors in the US have their own history and their own limits, and they are not the same question as the European one. Ask a US test house directly, and ask Acconeer what their customers have done. **This may be the constraint that decides which markets ship first.** |
| **Battery shipping** | the finished bag contains a lithium cell: **UN 3481**, packed with equipment. |

## 4 · Wireless power

The receiver is a **{bom.BOM['U11']['mpn']}** — a standard WPC 5 W receiver —
so any Qi pad speaks its language.

- ⚠️ **Using the Qi logo requires WPC membership and certification of the
  receiver.** Without it the product still works on Qi pads; it just cannot be
  called Qi in marketing or on the box.
- ⛔ **Foreign object detection is not certified, it is calibrated.** The
  transmitter compares the receiver's quality factor against a number the
  receiver declares, and that number has to be measured on the assembled bag.
  See `tools/calibrate.py`. A bag that declares a Q it does not have is a bag
  that charges with a coin on it.

## 5 · The order this actually happens in

⭐ **The 60 GHz question comes first and it is the only one that can kill the
design.** Everything else is cost and schedule; that one is a yes or a no, and
it wants answering before five prototypes are ordered rather than after.

1. **Ask Acconeer.** What route do their consumer customers take in the EU and
   the US, what test reports exist for the A121, and what transfers to a product
   that embeds it. One email, and it may answer most of section 2 and 3.
2. **Ask one test house for a scoping call.** They will want the table in
   section 1. That call is usually free and it produces the real standards list
   and a quote.
3. **Then order the prototypes** — the radiated measurements need a built board
   in a built bag, so the sample is the input to everything above anyway.
4. Battery paperwork, RoHS/REACH declarations, WEEE registration: these are
   administration and they follow the technical work.

## 6 · What this means for the schedule

⚠️ **Certification is measured in months and thousands, not days.** A full RED
route for a product with an unusual radiator is the longest single item between
here and a shipped box — longer than tooling the bag, longer than the PCB lead
times, longer than the firmware.

⛔ **And it is not in any plan in this repository.** That is the finding, and it
is why this file exists.
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(text)
    print(f"OK  {OUT}")
    for r in radiators():
        print(f"    {r['what']:<26} {r['band']}")
    print("\n  ⛔ THE 60 GHz QUESTION COMES FIRST. It is the only one that can")
    print("     kill the design rather than cost money, and it wants an answer")
    print("     before five prototypes are ordered rather than after.")
    print("     Two emails: Acconeer, and one test house for a scoping call.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
