#!/usr/bin/env python3
"""The fabrication note, generated from the files it describes.

⛔ A HAND-TYPED FAB NOTE DRIFTS. It says 0.1 mm because it said 0.1 mm last year,
and nobody notices when the project file changes. Every number below is read out
of hardware/smartbag_core.kicad_pro, the board itself, or dimensions.py at the
moment the note is written, so the note and the artwork cannot disagree.

Usage:  python3 tools/fab_notes.py > fab/README-FAB.md
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "hardware"))

import dimensions as dim               # noqa: E402
import bom                             # noqa: E402

PRO = os.path.join(ROOT, "hardware", "smartbag_core.kicad_pro")
PCB = os.path.join(ROOT, "hardware", "smartbag_core.kicad_pcb")

pro = json.load(open(PRO))
rules = pro["board"]["design_settings"]["rules"]
classes = {c["name"]: c for c in pro["net_settings"]["classes"]}
board = open(PCB).read()

layers = re.findall(r'\t\t\((\d+) "([^"]+)" (\w+)\)', board)
copper = [n for _i, n, t in layers if n.endswith(".Cu")]
vias = len(re.findall(r"\(via\b", board))
tracks = len(re.findall(r"\(segment\b", board))

print(f"""# SmartBag — fabrication notes

Generated by `tools/fab_notes.py`. Every figure here is read out of the project
file, the board, or `dimensions.py`, so it cannot drift away from the artwork
shipped beside it.

## ⛔ Read this before quoting

This board is **not releasable to production as it stands.** `tools/bom_report.py`
reports the reason in full; the short version is that three of the ICs are
footprints drawn for parts that were never chosen, and one of them
(the 60 GHz transceiver) is for a package that does not exist. Gerbers can be
plotted from any board file, including a wrong one — that is what this note is
here to say out loud.

Use these files for **DFM review and quotation**, not for a build.

## Board

| | |
|---|---|
| outline | {dim.BOARD_W:.0f} x {dim.BOARD_D:.0f} mm strip |
| copper layers | {len(copper)} — {' / '.join(copper)} |
| tracks / vias | {tracks} / {vias} |
| finished thickness | 0.6 mm rigid islands on polyimide flex |
| antenna areas | {dim.ANTENNA_SUBSTRATE_T} mm — see the stackup note below |

## Process

| rule | value |
|---|---|
| minimum track width | {rules['min_track_width']} mm |
| minimum clearance | {rules['min_clearance']} mm |
| minimum via diameter | {rules['min_via_diameter']} mm |
| minimum drill | {rules['min_through_hole_diameter']} mm |
| minimum annular ring | {rules['min_via_annular_width']} mm |
| hole to hole | {rules['min_hole_to_hole']} mm |
| copper to board edge | {rules['min_copper_edge_clearance']} mm |
| solder mask web | {rules['solder_mask_min_width']} mm |

⚠️ The mask web is {rules['solder_mask_min_width']} mm, not the usual 0.1 mm.
Fine-pitch QFN and 0402 land patterns genuinely cannot hold a wider web. Every
fab that accepts {rules['min_track_width']} mm lines accepts it, but it has to be
quoted, not assumed.

## What the design actually uses

| net class | track | clearance | via |
|---|---|---|---|""")

for name in ("Default", "Power", "RF_60G", "RF_24G"):
    c = classes.get(name)
    if c:
        print(f"| {name} | {c['track_width']} mm | {c['clearance']} mm | "
              f"{c['via_diameter']}/{c['via_drill']} mm |")

print(f"""
## ⛔ Stackup: the part a normal quote will get wrong

A `.kicad_pcb` carries **one** board thickness, and this design needs two. The
main board is a 0.6 mm rigid stack. The **antenna areas keep the flex core and a
thin stiffener only, {dim.ANTENNA_SUBSTRATE_T} mm to the reference plane.**

That is not a preference. `rf/patch_sim.py` solves the element full-wave on both:
on 0.6 mm it resonates at 50.8 GHz and reflects almost everything (-2.5 dB); on
{dim.ANTENNA_SUBSTRATE_T} mm the same patch matches at -27.2 dB with 3.5 GHz of
bandwidth. Build the antenna areas at full rigid thickness and the radar does not
work.

The note is on the **Cmts.User** layer of the artwork as well as here.

⚠️ See `tools/bom_report.py`: with a real 60 GHz part the antenna is inside the
chip package and these islands should not exist at all. If that change is made
first, this stackup requirement disappears with them.

## Files

| file | what |
|---|---|
| `gerbers/*.gbr` | RS-274X, X2 attributes on, mask subtracted from silk |
| `gerbers/*-PTH.drl`, `*-NPTH.drl` | Excellon, mm, absolute origin, **separate** |
| `gerbers/*-drl_map.gbr` | drill map |
| `smartbag-top.pos`, `smartbag-bottom.pos` | placement, mm, drill-file origin |
| `smartbag-bom.csv` | one row per placed part, with MPN where one is chosen |
| `bom-report.txt` | ⛔ the footprint-vs-datasheet check, including its failures |

⚠️ PTH and NPTH are separate files on purpose. Merged, a fab plates the mounting
holes.

## Assembly

- **{sum(1 for e in bom.BOM.values() if e['pitch'] and e['pitch'] <= 0.4)} parts at 0.4 mm pitch or finer.** Reflow only; nothing here is
  hand-solderable and the ground pours are set to solid pad connection rather
  than thermal relief for that reason.
- The board has **no fiducials**. ⛔ Add them before any real assembly quote —
  0.4 mm-pitch placement without fiducials is not a service anyone will offer.
- No panelisation, no tooling holes, no test points.
""")
