#!/usr/bin/env python3
"""The document a leather goods maker needs, generated from the design.

⛔ THE BAG HAS BEEN THE LEAST DEVELOPED PART OF THIS PROJECT AND THE REASON IS
THAT NOBODY WROTE THIS. The insert is engineered down to a 0.1 mm drill; the
thing it goes inside exists as a CAD study, a render and a paragraph. A maker
cannot quote from any of those.

⭐ AND THE HALF THAT MATTERS IS NOT THE DIMENSIONS, IT IS THE CONSTRAINTS. The
electronics impose four rules on the bag, and every one of them is a rule a
competent bag maker would break without knowing:

  - metal feet on the base are standard practice on a structured bag, and they
    would sit between the charging coil and the pad;
  - a magnetic closure is the obvious choice, and the wrong magnet in the wrong
    place either blinds the sensor that wakes the product or holds it awake;
  - lining the base in anything with a metallised backing kills the charging;
  - a base thicker than the leather it was designed around moves the coil out
    of range, and the range is already tight.

None of those are preferences. They are the reason this file is generated from
dimensions.py and bom.py rather than typed, so that a change to the design
reaches the person cutting the hides.

Usage:  python3 tools/tech_pack.py        (writes docs/tech-pack.md)
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "cad"))
sys.path.insert(0, os.path.join(ROOT, "hardware"))

import dimensions as d              # noqa: E402
import patterns                     # noqa: E402
import bom                          # noqa: E402
import qi_resonance as qi           # noqa: E402

OUT = os.path.join(ROOT, "docs", "tech-pack.md")


def main():
    sets = patterns.panels()
    coil_d = 2 * d.QI_R_OUT
    # ⚠️ The number that decides whether a standard charging pad works. The coil
    # recess is open at the bottom of the insert, the insert sits on the bag's
    # inner floor, so what separates the two coils is the bag's own base.
    gap = d.LEATHER
    cell = bom.BOM["BT1"]

    rows = []
    total = 0.0
    for name, count, pts, note in sets:
        a = patterns.area(patterns.offset(pts, patterns.SEAM)) / 100.0
        total += a * count
        w = max(p[0] for p in pts) - min(p[0] for p in pts) + 2 * patterns.SEAM
        h = max(p[1] for p in pts) - min(p[1] for p in pts) + 2 * patterns.SEAM
        rows.append(f"| **{name.replace('_', '/')}** | {count} | "
                    f"{w:.0f} × {h:.0f} mm | {note} |")

    text = f"""# SmartBag — tech pack

⚠️ **Generated by `tools/tech_pack.py` from `dimensions.py`, `hardware/bom.py`
and `cad/patterns.py`.** Do not edit this file; edit the design and run it again.
Everything below is derived, so a change to the bag reaches the person cutting
the hides instead of stopping at a CAD model.

⛔ **This is a first pattern, and that is how the trade works.** You cannot unroll
a 3D loft into a leather pattern and cut hides from it: a structured bag gets its
shape from the stiffener and the stitching as much as from the outline, leather
stretches on the bias and not across it, and every maker eases a curve
differently. Cut a toile in cheap material first. Two or three iterations before
the pattern is right is normal and none of them are a fault in this document.

---

## 1 · The bag

| | |
|---|---|
| silhouette | flared trapezoid, rigid body then a soft neck |
| base | **{d.BAG_W_BOTTOM:.0f} × {d.BAG_D_BOTTOM:.0f} mm**, R{d.CORNER_R:.0f} vertical corners |
| at the top of the rigid body | **{d.BAG_W_TOP:.0f} × {d.BAG_D_TOP:.0f} mm**, R{d.CORNER_R + 2:.0f} |
| rigid height | **{d.BAG_H:.0f} mm** |
| mouth | **{d.BAG_MOUTH_Z:.0f} mm** from the base — the last {d.BAG_MOUTH_Z - d.BAG_H:.0f} mm is the soft neck |
| leather | structured, **{d.LEATHER:.1f} mm** finished thickness |
| handles | rolled, attached at **z = {d.HANDLE_Z:.0f} mm** — to the body, not the rim |

⚠️ **The handles do not go on the rim.** The neck pinches shut; a handle stitched
to the rim hangs in mid-air the moment the bag is closed.

## 2 · Cut list

Patterns: [`fab/patterns/smartbag-patterns.dxf`](../fab/patterns/smartbag-patterns.dxf),
1:1 in millimetres. **CUT** layer is the cutting line, **SEAM** the stitch line,
{patterns.SEAM:.0f} mm apart.

| panel | ×  | cut size | note |
|---|---|---|---|
{chr(10).join(rows)}

**Leather, panels only: {total:.0f} cm² ({total / 929.03:.2f} sq ft).** At a
realistic 65% yield once the belly, the brands and the scars are avoided, about
**{total / 929.03 / 0.65:.2f} sq ft a bag** — before lining, stiffener,
reinforcement patches and the closure, which roughly double it.

---

## 3 · What the electronics require — these are specifications

### 3.1 ⛔ The charging window: Ø{coil_d + 8:.0f} mm at the centre of the base

A **Ø{coil_d:.0f} mm** wireless charging coil sits at the exact centre of the
insert's underside, facing down through the base of the bag. Inside a
**Ø{coil_d + 8:.0f} mm** circle centred on the base:

- ⛔ **no metal of any kind.** No feet, no rivets, no plate, no magnetic snaps,
  no metallised or foil-backed lining, no metal-cored stiffener.
- ⛔ **base thickness {gap:.1f} mm and not more.** This is the gap between the
  two coils and it is already most of the budget: a standard pad works to about
  5 mm coil to coil, and {gap:.1f} mm of leather plus the pad's own surface uses
  it up. A doubled base or a thick reinforcement here stops the bag charging and
  will look like an electronics fault.
- ✅ leather, fabric lining, non-woven stiffener, thread and glue are all fine.
  The field does not care about them.

⚠️ **Metal feet are standard practice on a bag this size and they are the single
most likely thing to go wrong.** If the bag needs feet, they go **outside** the
Ø{coil_d + 8:.0f} mm circle and they should be non-metallic.

### 3.2 ⛔ The closure magnet wakes the product

The insert has a magnetic sensor in its collar: it is what tells the bag it has
been opened, and the entire power budget depends on it. Everything else is
asleep until the closure opens.

- the closure **must** carry a small permanent magnet;
- it has to pass within about **5 mm** of the insert collar when the bag shuts;
- ⛔ **one magnet, and no other magnets anywhere in the bag.** A magnetic
  pocket snap near the collar holds the product permanently awake, which shows
  up as a battery that lasts days instead of months;
- ⛔ **no magnet within Ø{coil_d + 8:.0f} mm of the base centre** — see 3.1.

### 3.3 The insert pocket

The insert is a rigid tray that drops into the bag and sits on its inner floor.

| | |
|---|---|
| footprint | **{d.INS_W:.0f} × {d.INS_D:.0f} mm**, R{d.INS_R:.0f} |
| height | **{d.INS_TOTAL_H:.1f} mm** |
| bag inner at the base | {d.BAG_W_BOTTOM - 2 * d.LEATHER:.0f} × {d.BAG_D_BOTTOM - 2 * d.LEATHER:.0f} mm |
| clearance | **{(d.BAG_W_BOTTOM - 2 * d.LEATHER - d.INS_W) / 2:.1f} mm** each side, **{(d.BAG_D_BOTTOM - 2 * d.LEATHER - d.INS_D) / 2:.1f} mm** front and back |

⚠️ **That clearance is small and it is where a lining goes.** A padded or quilted
lining on the lower walls does not leave room for the insert. Line the walls flat.

### 3.4 The cell is a lithium pouch

{cell['mpn']} — {cell['capacity_mah']} mAh, in the insert, not in the bag. It
never comes out and there is no user-accessible battery door.

- ⛔ nothing in the construction may compress the base of the insert;
- ⚠️ the finished bag ships with a cell in it, which is a **UN 3481** shipment
  and needs the paperwork. The cell itself is already **UN 38.3** and
  **IEC 62133-2** certified by its maker — that is on its datasheet — but the
  finished product is a separate declaration.

---

## 4 · What is still open on the bag

Everything in section 3 is settled. None of the following is:

- ⛔ **no maker.** No pellettiere has seen this, no sample has been sewn, no
  quote exists.
- ⛔ **no closure chosen.** The neck has to pinch shut and carry a magnet;
  whether that is a zip, a magnetic flap or a drawstring is a design decision
  nobody has taken, and it changes the neck pattern.
- ⛔ **no lining or stiffener specified.** Which stiffener a structured bag uses
  decides how the panels are cut, so this comes before the pattern is final.
- ⛔ **no hardware.** Handle fixings, feet if any, closure hardware.
- ⚠️ **the pattern has never been cut.** See the note at the top: expect two or
  three iterations with the maker.

---

## 5 · How to read the rest of the repository

| you want | look at |
|---|---|
| the shape in 3D | `cad/bag_and_insert.py`, and `render/views/section.png` |
| what goes inside | `README.md`, "The circuit" |
| why the coil is where it is | `thermal/budget.py` — it moved the cell, not the coil |
| the numbers behind this file | `dimensions.py` |
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(text)
    print(f"OK  {OUT}")
    print(f"    {len(sets)} panels, {total:.0f} cm2 of leather, "
          f"4 hard constraints on the maker")
    # ⚠️ The one number a bag maker can silently break and nobody would find out
    # until a prototype refuses to charge on a pad.
    print(f"\n  ⛔ the charging window is Ø{coil_d + 8:.0f} mm at the centre of "
          f"the base and the base\n     may not exceed {gap:.1f} mm. Metal feet "
          f"are standard practice and would\n     sit right in it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
